# Generated by Django 5.2.11 on 2026-02-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0003_alter_booth_id_alter_boothimage_id_alter_division_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="질문 내용"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="퀴즈 순서 (1~6)", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "퀴즈 질문",
                "verbose_name_plural": "퀴즈 질문들",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(max_length=255, verbose_name="선택지 텍스트"),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_options",
                        to="main.division",
                        verbose_name="연결된 분과",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.quiz",
                        verbose_name="해당 질문",
                    ),
                ),
            ],
            options={
                "verbose_name": "퀴즈 선택지",
                "verbose_name_plural": "퀴즈 선택지들",
            },
        ),
    ]
