# Generated by Django 5.2.7 on 2026-02-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "booth_type",
                    models.CharField(
                        choices=[("CLUB", "CLUB"), ("FOODTRUCK", "FOODTRUCK")],
                        default="CLUB",
                        max_length=20,
                    ),
                ),
                ("loc_num", models.PositiveIntegerField()),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("event", models.TextField(blank=True, default="")),
                ("recruit_start", models.DateField(blank=True, null=True)),
                ("recruit_end", models.DateField(blank=True, null=True)),
                (
                    "recruit_detail",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "instagram_handle",
                    models.CharField(blank=True, max_length=31, null=True),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booths",
                        to="main.division",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booths",
                        to="main.location",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booths",
                        to="main.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("team_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="timetable/"),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetables",
                        to="main.booth",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetables",
                        to="main.location",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetables",
                        to="main.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="BoothImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="booths/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.booth",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booth", "order"), name="unique_booth_image_order"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booth",
            constraint=models.UniqueConstraint(
                fields=("schedule", "location", "loc_num"),
                name="unique_booth_locnum_per_day_location",
            ),
        ),
    ]
