# Generated by Django 6.0.2 on 2026-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_booth_id_alter_boothimage_id_alter_division_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="menu",
            field=models.TextField(blank=True, default=""),
        ),
    ]
